package com.java.Day3;

public class ExectionExample2 {
	public static void main(String[] args) {
		
		try {
			System.out.println("A");
			int num = 99/0;
			System.out.println("B");
		} catch (ArithmeticException e) 
		{
			System.out.println("C");
			
		}catch (Exception e) {
			System.out.println("D");
		}finally {
			System.out.println("E");
		}
	}
	
	

}
